name: softwarequality
channels:
  - defaults
dependencies:
  - python=3.12
  - ipython
  - jupyter
  - jupyterlab
  - pandas
  - numpy
  - pip:
    - llama-cpp-python
    - huggingface-hub
    - transformers
    - sacrebleu
    - mlflow
    - datasets
    - sentencepiece
    - torch
    - accelerate
    - rouge-score
